import type {MapleBossConfig} from "@/types/mapleBossAnalysis";

export const MAPLE_BOSS_MAP: Record<string, MapleBossConfig> = {
    swoo_normal: {
        id: "swoo_normal",
        name: "스우",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 2_200_000_000,
    },
    swoo_hard: {
        id: "swoo_hard",
        name: "스우",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 7_400_000_000,
    },
    swoo_extreme: {
        id: "swoo_extreme",
        name: "스우",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 95_000_000_000,
    },
    damien_normal: {
        id: "damien_normal",
        name: "데미안",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 7_600_000_000,
    },
    damien_hard: {
        id: "damien_hard",
        name: "데미안",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 24_000_000_000,
    },
    guardian_angel_slime_normal: {
        id: "guardian_angel_slime_normal",
        name: "가디언 엔젤 슬라임",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 5_500_000_000,
    },
    guardian_angel_slime_chaos: {
        id: "guardian_angel_slime_chaos",
        name: "가디언 엔젤 슬라임",
        difficulty: "카오스",
        bossPdr: 3,
        bossRequiredDamageScore: 18_500_000_000,
    },
    lucid_easy: {
        id: "lucid_easy",
        name: "루시드",
        difficulty: "이지",
        bossPdr: 3,
        bossRequiredDamageScore: 5_000_000_000,
    },
    lucid_normal: {
        id: "lucid_normal",
        name: "루시드",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 9_800_000_000,
    },
    lucid_hard: {
        id: "lucid_hard",
        name: "루시드",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 28_000_000_000,
    },
    will_easy: {
        id: "will_easy",
        name: "윌",
        difficulty: "이지",
        bossPdr: 3,
        bossRequiredDamageScore: 5_400_000_000,
    },
    will_normal: {
        id: "will_normal",
        name: "윌",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 10_800_000_000,
    },
    will_hard: {
        id: "will_hard",
        name: "윌",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 31_000_000_000,
    },
    gloom_normal: {
        id: "gloom_normal",
        name: "더스크",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 13_000_000_000,
    },
    gloom_chaos: {
        id: "gloom_chaos",
        name: "더스크",
        difficulty: "카오스",
        bossPdr: 3,
        bossRequiredDamageScore: 32_000_000_000,
    },
    darknell_normal: {
        id: "darknell_normal",
        name: "듄켈",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 16_000_000_000,
    },
    darknell_hard: {
        id: "darknell_hard",
        name: "듄켈",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 36_000_000_000,
    },
    verus_hilla_normal: {
        id: "verus_hilla_normal",
        name: "진 힐라",
        difficulty: "노멀",
        bossPdr: 3,
        bossRequiredDamageScore: 18_000_000_000,
    },
    verus_hilla_hard: {
        id: "verus_hilla_hard",
        name: "진 힐라",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 42_000_000_000,
    },
    black_mage_hard: {
        id: "black_mage_hard",
        name: "검은 마법사",
        difficulty: "하드",
        bossPdr: 3,
        bossRequiredDamageScore: 58_000_000_000,
    },
    black_mage_extreme: {
        id: "black_mage_extreme",
        name: "검은 마법사",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 160_000_000_000,
    },
    seren_normal: {
        id: "seren_normal",
        name: "선택받은 세렌",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 27_500_000_000,
    },
    seren_hard: {
        id: "seren_hard",
        name: "선택받은 세렌",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 70_000_000_000,
    },
    seren_extreme: {
        id: "seren_extreme",
        name: "선택받은 세렌",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 175_000_000_000,
    },
    kalos_easy: {
        id: "kalos_easy",
        name: "감시자 칼로스",
        difficulty: "이지",
        bossPdr: 3.8,
        bossRequiredDamageScore: 36_000_000_000,
    },
    kalos_normal: {
        id: "kalos_normal",
        name: "감시자 칼로스",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 88_000_000_000,
    },
    kalos_chaos: {
        id: "kalos_chaos",
        name: "감시자 칼로스",
        difficulty: "카오스",
        bossPdr: 3.8,
        bossRequiredDamageScore: 190_000_000_000,
    },
    kalos_extreme: {
        id: "kalos_extreme",
        name: "감시자 칼로스",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 360_000_000_000,
    },
    kaling_easy: {
        id: "kaling_easy",
        name: "카링",
        difficulty: "이지",
        bossPdr: 3.8,
        bossRequiredDamageScore: 52_000_000_000,
    },
    kaling_normal: {
        id: "kaling_normal",
        name: "카링",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 115_000_000_000,
    },
    kaling_hard: {
        id: "kaling_hard",
        name: "카링",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 240_000_000_000,
    },
    kaling_extreme: {
        id: "kaling_extreme",
        name: "카링",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 430_000_000_000,
    },
    limbo_normal: {
        id: "limbo_normal",
        name: "림보",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 155_000_000_000,
    },
    limbo_hard: {
        id: "limbo_hard",
        name: "림보",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 330_000_000_000,
    },
    baldrix_normal: {
        id: "baldrix_normal",
        name: "발드릭스",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 190_000_000_000,
    },
    baldrix_hard: {
        id: "baldrix_hard",
        name: "발드릭스",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 380_000_000_000,
    },
    first_adversary_easy: {
        id: "first_adversary_easy",
        name: "최초의 대적자",
        difficulty: "이지",
        bossPdr: 3.8,
        bossRequiredDamageScore: 85_000_000_000,
    },
    first_adversary_normal: {
        id: "first_adversary_normal",
        name: "최초의 대적자",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 210_000_000_000,
    },
    first_adversary_hard: {
        id: "first_adversary_hard",
        name: "최초의 대적자",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 430_000_000_000,
    },
    first_adversary_extreme: {
        id: "first_adversary_extreme",
        name: "최초의 대적자",
        difficulty: "익스트림",
        bossPdr: 3.8,
        bossRequiredDamageScore: 720_000_000_000,
    },
    jupiter_normal: {
        id: "jupiter_normal",
        name: "유피테르",
        difficulty: "노멀",
        bossPdr: 3.8,
        bossRequiredDamageScore: 240_000_000_000,
    },
    jupiter_hard: {
        id: "jupiter_hard",
        name: "유피테르",
        difficulty: "하드",
        bossPdr: 3.8,
        bossRequiredDamageScore: 480_000_000_000,
    },
};

export function getBossConfig(bossId: string) {
    return MAPLE_BOSS_MAP[bossId] ?? null;
}
